#!/usr/bin/env python3
"""Digital-ESD real ERIC execution receipt compiler.

Consumes real-eric-screening-wrapper-receipt.json and independently checks:
  - 46,597 occurrence expectation
  - 43,996 unique expectation
  - real-ERIC flag
  - full-text stop boundary
  - all non-promotion booleans
  - every output artifact exists
  - every output artifact SHA-256 still matches

Then emits a concrete Agda value:
  observedRealERICExecution : Exec.RealERICStudyExecutionReceipt

containing the actual paths/hashes from that run.

Trust chain:
  raw ERIC JSON
    ↓ page SHA verification
digital_esd_eric.py
    ↓
43,996 real metadata records
    ↓ artifact SHA
run_digital_esd_real_eric.py
    ↓ runtime receipt JSON
emit_digital_esd_eric_execution_agda.py
    ↓ concrete Agda RealERICStudyExecutionReceipt
"""
from __future__ import annotations

import argparse
import hashlib
import json
import logging
import sys
from pathlib import Path

logger = logging.getLogger("eric_receipt_compiler")
logger.setLevel(logging.INFO)
if not logger.handlers:
    logger.addHandler(logging.StreamHandler(sys.stderr))

EXPECTED_OCCURRENCES = 46597
EXPECTED_UNIQUE = 43996


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def emit_agda(receipt_path: Path, output_path: Path) -> dict:
    """Emit a concrete Agda value from the receipt."""
    with open(receipt_path) as fh:
        receipt = json.load(fh)

    # Validate all expectations
    errors: list[str] = []

    if receipt["observed_raw_occurrences"] != EXPECTED_OCCURRENCES:
        errors.append(
            f"raw occurrences mismatch: {receipt['observed_raw_occurrences']} != {EXPECTED_OCCURRENCES}"
        )
    if receipt["observed_unique_records"] != EXPECTED_UNIQUE:
        errors.append(
            f"unique records mismatch: {receipt['observed_unique_records']} != {EXPECTED_UNIQUE}"
        )
    if not receipt["real_eric"]:
        errors.append("real_ERIC flag is not true")
    if not receipt["full_text_stop"]:
        errors.append("full_text_stop boundary is not true")
    if not receipt.get("screening_ledger_all_unresolved", False):
        errors.append("screening_ledger_all_unresolved must be true")
    if receipt.get("scalar_screening_score_used", True):
        errors.append("scalar_screening_score_used must be false")
    if receipt["creates_screening_decision"]:
        errors.append("creates_screening_decision must be false")
    if receipt["creates_source_truth"]:
        errors.append("creates_source_truth must be false")
    if receipt["creates_source_audit_admission"]:
        errors.append("creates_source_audit_admission must be false")
    if not receipt["counts_match"]:
        errors.append("counts do not match expected values")

    # Verify every bound artifact still exists and matches its receipt hash.
    artifact_paths = receipt.get("artifact_paths", {})
    artifact_hashes = receipt.get("artifact_hashes", {})
    if set(artifact_paths) != set(artifact_hashes):
        errors.append(
            "artifact path/hash key sets differ: "
            f"paths={sorted(artifact_paths)} hashes={sorted(artifact_hashes)}"
        )
    for name in sorted(set(artifact_paths) | set(artifact_hashes)):
        path_text = artifact_paths.get(name)
        expected_hash = artifact_hashes.get(name)
        if not path_text or not expected_hash:
            errors.append(f"{name}: missing artifact path or hash")
            continue
        artifact_path = Path(path_text)
        if not artifact_path.exists() or not artifact_path.is_file():
            errors.append(f"{name}: artifact missing: {artifact_path}")
            continue
        observed_hash = sha256_file(artifact_path)
        if observed_hash != expected_hash:
            errors.append(
                f"{name}: artifact digest drift: "
                f"expected {expected_hash}, observed {observed_hash}"
            )

    if errors:
        logger.error("Receipt validation failed:")
        for e in errors:
            logger.error("  - %s", e)
        raise ValueError(f"Receipt validation failed: {len(errors)} errors")

    # Emit a concrete value of the canonical DASHI receipt type.
    hashes = receipt["artifact_hashes"]
    paths = receipt["artifact_paths"]
    agda_lines = [
        "-- Auto-generated by emit_digital_esd_eric_execution_agda.py",
        "-- Do not edit manually.",
        "-- Generated only after receipt + artifact revalidation.",
        "",
        "module DASHI.Generated.DigitalESDERICStudyExecutionObserved where",
        "",
        "open import Agda.Builtin.Bool using (false; true)",
        "open import Agda.Builtin.Equality using (refl)",
        "import DASHI.Education.DigitalESDERICStudyExecutionExact as Exec",
        "",
        "observedRealERICExecution : Exec.RealERICStudyExecutionReceipt",
        "observedRealERICExecution = Exec.real-eric-study-execution-receipt",
        "  " + json.dumps(receipt["run_id"]),
        "  " + json.dumps(receipt["started_at"]),
        "  " + json.dumps(receipt["completed_at"]),
        "  46597",
        "  46597",
        "  refl",
        "  43996",
        "  43996",
        "  refl",
        "  true",
        "  refl",
        "  true",
        "  refl",
        "  true",
        "  refl",
        "  false",
        "  refl",
        "  false",
        "  refl",
        "  false",
        "  refl",
        "  false",
        "  refl",
        "  " + json.dumps(paths["parsed_metadata_corpus"]),
        "  " + json.dumps(hashes["parsed_metadata_corpus"]),
        "  " + json.dumps(paths["parser_manifest"]),
        "  " + json.dumps(hashes["parser_manifest"]),
        "  " + json.dumps(paths["screening_ledger"]),
        "  " + json.dumps(hashes["screening_ledger"]),
        "  " + json.dumps(paths["candidate_assessment"]),
        "  " + json.dumps(hashes["candidate_assessment"]),
        "  " + json.dumps(paths["study_family_hypotheses"]),
        "  " + json.dumps(hashes["study_family_hypotheses"]),
        "  " + json.dumps(paths["calibration_selection"]),
        "  " + json.dumps(hashes["calibration_selection"]),
        "  " + json.dumps(paths["calibration_estimate"]),
        "  " + json.dumps(hashes["calibration_estimate"]),
        "  " + json.dumps(paths["pareto_queue"]),
        "  " + json.dumps(hashes["pareto_queue"]),
        "",
    ]

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as fh:
        fh.write("\n".join(agda_lines))

    logger.info("Agda receipt emitted: %s", output_path)
    logger.info("Observed: %d occurrences, %d unique records",
                receipt["observed_raw_occurrences"], receipt["observed_unique_records"])
    return receipt


def main() -> int:
    parser = argparse.ArgumentParser(description="Emit Agda real ERIC execution receipt")
    parser.add_argument("--receipt", type=Path, required=True,
                        help="Path to real-eric-screening-wrapper-receipt.json")
    parser.add_argument("--output", type=Path, required=True,
                        help="Output Agda file path")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    if not args.receipt.exists():
        logger.error("Receipt not found: %s", args.receipt)
        return 1

    receipt = emit_agda(args.receipt, args.output)

    if args.json:
        print(json.dumps({"status": "ok", "output": str(args.output),
                          "observed": receipt["observed_unique_records"]}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
